require('dotenv').config();
const sequelize = require('../config/configDb');
const SysHojaVida = require('../models/Sistemas/SysHojaVida');

// IDs de los equipos insertados: 2 al 11
const hojasVida = [
  {
    id_sysequipo_fk: 2,
    ip: '192.168.1.101',
    mac: 'A4:C3:F0:11:22:01',
    procesador: 'Intel Core i5-10500',
    ram: '8 GB DDR4',
    disco_duro: '256 GB SSD',
    sistema_operativo: 'Windows 10 Pro',
    office: 'Microsoft 365',
    nombre_usuario: 'admin.sistemas',
    vendedor: 'HP Colombia S.A.S',
    tipo_uso: 'Administrativo',
    fecha_compra: '2022-03-10',
    fecha_instalacion: '2022-03-15',
    costo_compra: '3200000',
    contrato: 'CONT-2022-001',
    observaciones: 'Equipo principal de la oficina administrativa. En buen estado.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 3,
    ip: '192.168.2.50',
    mac: 'B8:27:EB:22:33:02',
    procesador: 'Intel Core i7-10700',
    ram: '16 GB DDR4',
    disco_duro: '512 GB SSD',
    sistema_operativo: 'Windows 10 Pro',
    office: 'Microsoft 365',
    nombre_usuario: 'urgencias.enf',
    vendedor: 'Dell Technologies Colombia',
    tipo_uso: 'Asistencial',
    fecha_compra: '2021-07-15',
    fecha_instalacion: '2021-07-20',
    costo_compra: '4500000',
    contrato: 'CONT-2021-015',
    observaciones: 'Equipo crítico de urgencias. Requiere mantenimiento preventivo semestral.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 4,
    ip: '192.168.3.20',
    mac: 'DC:A6:32:33:44:03',
    procesador: 'Intel Core i5-11400T',
    ram: '8 GB DDR4',
    disco_duro: '256 GB SSD',
    sistema_operativo: 'Windows 11 Pro',
    office: 'Microsoft 365',
    nombre_usuario: 'consulta.externa3',
    vendedor: 'Lenovo Colombia',
    tipo_uso: 'Asistencial',
    fecha_compra: '2023-01-05',
    fecha_instalacion: '2023-01-10',
    costo_compra: '2800000',
    contrato: 'CONT-2023-003',
    observaciones: 'Equipo asignado al Consultorio 3. Windows 11 actualizado.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 5,
    ip: '192.168.4.10',
    mac: 'E4:5F:01:44:55:04',
    procesador: 'Intel Core i7-10700',
    ram: '16 GB DDR4',
    disco_duro: '1 TB SSD',
    sistema_operativo: 'Windows 10 Pro',
    office: 'Microsoft 365',
    nombre_usuario: 'lab.clinico',
    vendedor: 'HP Colombia S.A.S',
    tipo_uso: 'Laboratorio',
    fecha_compra: '2022-09-01',
    fecha_instalacion: '2022-09-05',
    costo_compra: '5200000',
    contrato: 'CONT-2022-022',
    observaciones: 'Equipo del laboratorio clínico. Software de análisis instalado.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 6,
    ip: '192.168.5.5',
    mac: 'F4:CE:36:55:66:05',
    procesador: 'Intel Xeon W-1250',
    ram: '32 GB DDR4 ECC',
    disco_duro: '2 TB NVMe',
    sistema_operativo: 'Windows 10 Pro for Workstations',
    office: 'Microsoft 365',
    nombre_usuario: 'rayosx.tecnico',
    vendedor: 'Dell Technologies Colombia',
    tipo_uso: 'Diagnóstico por imagen',
    fecha_compra: '2023-04-10',
    fecha_instalacion: '2023-04-18',
    costo_compra: '8500000',
    contrato: 'CONT-2023-010',
    observaciones: 'Workstation de alta gama para procesamiento de imágenes radiológicas. Licencias especiales instaladas.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 7,
    ip: '192.168.1.200',
    mac: '00:14:22:66:77:06',
    procesador: 'Intel Core i3-10100',
    ram: '4 GB DDR4',
    disco_duro: '500 GB HDD',
    sistema_operativo: 'Windows 10 Home',
    office: 'Microsoft Office 2019',
    nombre_usuario: 'facturacion.vent1',
    vendedor: 'Lenovo Colombia',
    tipo_uso: 'Administrativo',
    fecha_compra: '2021-02-20',
    fecha_instalacion: '2021-02-28',
    costo_compra: '1800000',
    contrato: 'CONT-2021-005',
    observaciones: 'Equipo inactivo. Pendiente revisión técnica. Posible falla en fuente de poder.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 8,
    ip: '192.168.1.201',
    mac: '00:14:22:77:88:07',
    procesador: 'Intel Core i5-10500',
    ram: '8 GB DDR4',
    disco_duro: '256 GB SSD',
    sistema_operativo: 'Windows 10 Pro',
    office: 'Microsoft 365',
    nombre_usuario: 'facturacion.vent2',
    vendedor: 'HP Colombia S.A.S',
    tipo_uso: 'Administrativo',
    fecha_compra: '2021-02-20',
    fecha_instalacion: '2021-02-28',
    costo_compra: '2900000',
    contrato: 'CONT-2021-005',
    observaciones: 'Ventanilla 2 de facturación. En buen estado operativo.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 9,
    ip: '192.168.1.5',
    mac: '3C:06:30:88:99:08',
    procesador: 'Apple M2',
    ram: '8 GB Unificada',
    disco_duro: '256 GB SSD NVMe',
    sistema_operativo: 'macOS Ventura 13.5',
    office: 'Microsoft 365',
    nombre_usuario: 'gerente.general',
    vendedor: 'Apple Colombia',
    tipo_uso: 'Gerencial',
    fecha_compra: '2023-07-25',
    fecha_instalacion: '2023-08-01',
    costo_compra: '7200000',
    contrato: 'CONT-2023-020',
    observaciones: 'Equipo de la Gerencia General. Garantía vigente hasta 2025.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 10,
    ip: '192.168.2.100',
    mac: '5C:BA:EF:99:AA:09',
    procesador: 'Intel Core i5-10500T',
    ram: '8 GB DDR4',
    disco_duro: '512 GB SSD',
    sistema_operativo: 'Windows 10 Pro',
    office: 'Microsoft 365',
    nombre_usuario: 'uci.central',
    vendedor: 'Dell Technologies Colombia',
    tipo_uso: 'Asistencial',
    fecha_compra: '2022-11-10',
    fecha_instalacion: '2022-11-14',
    costo_compra: '3800000',
    contrato: 'CONT-2022-035',
    observaciones: 'Equipo de la estación central UCI. Mantenimiento preventivo al día.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  },
  {
    id_sysequipo_fk: 11,
    ip: '192.168.1.150',
    mac: '70:F3:95:AA:BB:10',
    procesador: 'Intel Core i3-10100',
    ram: '4 GB DDR4',
    disco_duro: '500 GB HDD',
    sistema_operativo: 'Windows 10 Home',
    office: 'Microsoft Office 2016',
    nombre_usuario: 'archivo.clinico',
    vendedor: 'Lenovo Colombia',
    tipo_uso: 'Administrativo',
    fecha_compra: '2020-06-05',
    fecha_instalacion: '2020-06-10',
    costo_compra: '1500000',
    contrato: 'CONT-2020-008',
    observaciones: 'Equipo antiguo del archivo clínico. Inactivo por obsolescencia. Candidato a dar de baja.',
    compraddirecta: true,
    convenio: false,
    donado: false,
    comodato: false
  }
];

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Conexión a la base de datos exitosa.');

    const result = await SysHojaVida.bulkCreate(hojasVida, { validate: true });
    console.log(`✅ Se crearon ${result.length} hojas de vida correctamente.`);
    result.forEach(hv => {
      console.log(`  [HV-${hv.id_syshoja_vida}] → Equipo ID ${hv.id_sysequipo_fk}`);
    });
  } catch (error) {
    console.error('❌ Error al crear hojas de vida:', error.message);
  } finally {
    await sequelize.close();
  }
}

seed();
